### ISSUE TITLE
pytorch_scatter unbuildable

### ISSUE THREAD

**Issue by pgunn** [conda-forge/pytorch_scatter-feedstock#17]
Hi @oblute ,
I was curious when the packages would get built and asked about it on the conda-forge gitter; they said that the current flags in your meta.yaml mean this feedstock won't ever get built.

![pytorch_scatter_feedstock_issues](https://user-images.githubusercontent.com/829791/115452761-d9997a00-a1ec-11eb-9b13-72b4348b7301.jpg)

Could you work this out with them (possibly hopping on gitter) so new packages get built? Sorry for the fuss.

CC:
@isuruf

**Comment by rluria14** [comment]
@pgunn @oblute this should be resolved with the latest build. thanks for bringing this up!

**Comment by pgunn** [comment]
Just saw the files start to show up here. Awesome

https://anaconda.org/conda-forge/pytorch_scatter/files
